### ISSUE TITLE
GTK3 TODO

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#112]
Some of this work is done in #59.

Simple:
- [ ] CMakeLists.txt: add option to select which GTK version to build for

Simple, but tedious:
Mostly just using accessor functions instead of direct access (https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html#id-1.6.3.3.5)
- [ ] shell/shell.c
- [ ] shell/callbacks.c
- [ ] shell/report.c
- [ ] hardinfo/util.c

More work required:
- [ ] loadgraph (includes/loadgraph.h and shell/loadgraph.c): convert from gdk to cairo
- [ ] shell/iconcache.c: convert from gdk-pixbuf to _something_, perhaps cairo-png

Heavy work required, but low priority:
- [ ] modules/benchmark/guibench.c needs much work, could probably be disabled in the GTK3 build for now

**Comment by lpereira** [comment]
As far as the load graph goes, it might be a good idea to use this instead of just porting the current code to Cairo: https://github.com/chergert/uber-graph

It supports multiple graphs, looks nicer, etc.

**Comment by bp0** [comment]
That may be better, but would it be easier?

**Comment by lpereira** [comment]
It's not going to be easier, no. For the porting work it might be better to stick with the conversion from GDK drawing primitives to Cairo. Maybe afterwards move it to uber-graph.

**Comment by bp0** [comment]
Right, I just want to see it build for gtk3. I still have the link problem that I mentioned at #59.

**Comment by bp0** [comment]
GTK3 Hardinfo (in XFCE)
![hardinfo-gtk3](https://user-images.githubusercontent.com/1758090/28562714-07953540-70e9-11e7-9b90-f5bc4b822289.png)
Broken:
![hardinfo-gtk3-ohno](https://user-images.githubusercontent.com/1758090/28562717-0890e160-70e9-11e7-8b0f-6f9243800791.png)

**Comment by bp0** [comment]
@lpereira 
I was wrong. Just using uber-graph was significantly easier. Check out #114.

**Comment by bp0** [comment]
GTK3 and uber-graph:
![temp-spike](https://user-images.githubusercontent.com/1758090/28637630-d4ed1dd6-7207-11e7-9673-fc3be0db43c0.png)
