### ISSUE TITLE
For Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#216]
Debian Import Freeze is 1 March. It takes 5 days to accept changes to a package? (@tsimonq2) So deadline may be 23 February.
- [x] Package ID of -1 causes problems, fixed by #211
- [x] Cache id not available on all kernels, Fixed as part of #209
- [x] Truncated flags list on x86. Fixed as part of #214, a rewrite of the cpuinfo reading functions for all processor.c could come in the future.
- [x] Benchmark bugs and result errors. Needs at least #213, but the complete #212 would be nice
- [x] Crash while generating HTML report (#217), fixed in #218 

#212 needs discussion, but everything else should not be controversial. 

Tracking:
- [x] https://tracker.debian.org/pkg/hardinfo
- [x] https://packages.ubuntu.com/bionic/x11/hardinfo

**Comment by tsimonq2** [comment]
If needed, I now have upload access to Ubuntu, so I can fasttrack an upload before Feature Freeze.

Let me know when I should upload another upstream snapshot, and I'll do it.

Thank you!

**Comment by bp0** [comment]
@ipereira not much time left. Do you have concerns about these patches?

**Comment by tsimonq2** [comment]
@bp0 (cc @lpereira) We're about 30 hours away from the Feature Freeze in Ubuntu. Would you like me to upload it as-is, or would you like me to wait and file a Feature Freeze exception bug report?

**Comment by lpereira** [comment]
It's a lot of code to review -- I don't have much time to do this any longer. I'm applying some of @bp0's patches without reviewing them.

**Comment by bp0** [comment]
Thanks

**Comment by tsimonq2** [comment]
I'll get a new hardinfo uploaded to Debian as soon as possible.

**Comment by tsimonq2** [comment]
Sent to my sponsors.

I was going through bugs and I found [one with a patch ready](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=492989), you might consider accepting it upstream.

Thanks!

**Comment by tsimonq2** [comment]
It was just uploaded to Debian and should land in Ubuntu automatically before Feature Freeze.

**Comment by bp0** [comment]
Hey, it landed. Thanks, Simon!
