### ISSUE TITLE
Computer/Display information TODO

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#225]
The Computer/Display component of hardinfo is out of date. 

Things to work on:
- [ ] Use `xrandr` to get cards, outputs, and monitors (Don't use GNOME stuff, would fix #200) 
- [ ] Properly interpret core and compatibility profiles for OpenGL and OpenGL ES, and for each card, via `glxinfo` (#27, #170 was an attempt, but I don't think a correct one)
- [ ] Get Vulkan information `vulkaninfo` (fix #171)

**Comment by mckaygerhard** [comment]
umm! this are a "mini" TODO, not a TODO 

^_^u
